project: vulkan-lib
current_target: vulkan-lib
targets:
  vulkan-lib: Executable
modules:
  glfw:
    git_url: https://github.com/glfw/glfw
    git_version: '3.4'
    include_path: include
    link_name: glfw
  glm:
    git_url: https://github.com/g-truc/glm
    git_version: 1.0.2
  vulkan:
    git_url: https://github.com/KhronosGroup/Vulkan-Headers
    git_version: v1.4.332
    include_path: include
